package CompilerDesign;/* The following code was generated by JFlex 1.7.0 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/root/IdeaProjects/RegularExpressionTest/src/CompilerDesign/sample.flex</tt>
 */
class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\63\1\3\1\1\22\0\1\3\1\51\1\25"+
    "\2\0\1\50\1\4\1\23\1\55\1\56\1\27\1\45\1\53\1\47"+
    "\1\22\1\26\1\10\11\6\1\54\1\24\1\43\1\46\1\44\2\0"+
    "\6\7\24\5\1\61\1\0\1\62\1\0\1\5\1\0\1\17\1\40"+
    "\1\35\1\31\1\15\1\16\1\41\1\34\1\30\2\5\1\20\1\5"+
    "\1\37\1\32\1\42\1\5\1\13\1\21\1\12\1\14\1\36\1\33"+
    "\1\11\2\5\1\57\1\52\1\60\7\0\1\63\u1fa2\0\1\63\1\63"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\2\4\5\3\2\1"+
    "\1\5\1\1\1\6\1\7\7\3\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\1\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\0"+
    "\6\3\6\0\1\31\1\32\1\3\1\33\12\3\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\4\3\3"+
    "\1\43\2\3\1\44\1\45\1\0\1\46\3\3\1\47"+
    "\11\3\1\50\1\3\1\51\4\3\1\52\1\53\1\3"+
    "\1\54\1\55\4\3\1\56\2\3\1\57\1\60\4\3"+
    "\1\61\1\62\1\63\3\3\1\64\1\65\1\66\2\3"+
    "\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\64\0\234\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\64"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4"+
    "\0\u0618\0\u064c\0\64\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\u0270\0\u0680\0\u06b4\0\u06e8\0\u071c"+
    "\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u02d8\0\u0854\0\u0888"+
    "\0\u08bc\0\64\0\320\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0"+
    "\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\u0680\0\u0b60"+
    "\0\u0b94\0\u0bc8\0\320\0\u0bfc\0\u0c30\0\64\0\64\0\u0c64"+
    "\0\320\0\u0c98\0\u0ccc\0\u0d00\0\320\0\u0d34\0\u0d68\0\u0d9c"+
    "\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\320\0\u0f08"+
    "\0\320\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\320\0\320\0\u100c"+
    "\0\320\0\320\0\u1040\0\u1074\0\u10a8\0\u10dc\0\320\0\u1110"+
    "\0\u1144\0\320\0\320\0\u1178\0\u11ac\0\u11e0\0\u1214\0\320"+
    "\0\320\0\320\0\u1248\0\u127c\0\u12b0\0\320\0\320\0\320"+
    "\0\u12e4\0\u1318\0\320";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\6\1\10"+
    "\2\6\1\11\1\6\1\12\1\13\1\6\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\6\1\26\1\6\1\27\1\30\1\6\1\31\1\6"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\67\0\1\4\65\0\1\53\1\6\1\0\1\6"+
    "\1\0\11\6\6\0\13\6\26\0\15\6\6\0\13\6"+
    "\27\0\1\7\1\0\1\7\11\0\1\54\47\0\1\7"+
    "\1\0\1\7\1\55\10\0\1\54\46\0\10\6\1\56"+
    "\4\6\6\0\13\6\26\0\13\6\1\57\1\6\6\0"+
    "\13\6\26\0\13\6\1\60\1\6\6\0\2\6\1\61"+
    "\10\6\26\0\15\6\6\0\2\6\1\62\10\6\26\0"+
    "\5\6\1\63\7\6\6\0\13\6\27\0\1\54\1\0"+
    "\1\54\60\0\1\64\1\0\1\64\1\0\11\64\1\0"+
    "\1\65\4\0\13\64\26\0\1\66\1\0\1\66\1\0"+
    "\11\66\3\0\1\67\2\0\13\66\47\0\1\70\1\71"+
    "\16\0\1\72\22\0\1\6\1\0\1\6\1\0\11\6"+
    "\6\0\13\6\3\0\1\72\22\0\11\6\1\73\3\6"+
    "\6\0\7\6\1\74\3\6\26\0\15\6\6\0\2\6"+
    "\1\75\10\6\26\0\15\6\6\0\4\6\1\76\6\6"+
    "\26\0\13\6\1\77\1\6\6\0\1\100\1\6\1\101"+
    "\1\6\1\102\6\6\26\0\15\6\6\0\1\103\1\6"+
    "\1\104\10\6\26\0\15\6\6\0\2\6\1\105\10\6"+
    "\26\0\6\6\1\106\1\107\5\6\6\0\13\6\64\0"+
    "\1\110\2\0\1\111\61\0\1\112\1\0\1\113\62\0"+
    "\2\72\63\0\1\114\63\0\2\72\62\0\1\72\63\0"+
    "\1\115\67\0\1\116\17\0\3\117\4\0\3\117\11\0"+
    "\1\117\3\0\1\117\2\0\1\117\30\0\5\6\1\120"+
    "\7\6\6\0\13\6\26\0\14\6\1\121\6\0\13\6"+
    "\26\0\15\6\6\0\2\6\1\122\10\6\26\0\6\6"+
    "\1\123\6\6\6\0\13\6\26\0\15\6\6\0\7\6"+
    "\1\124\3\6\26\0\6\6\1\125\6\6\6\0\13\6"+
    "\44\0\1\65\64\0\1\126\63\0\1\127\37\0\1\70"+
    "\1\3\1\4\61\70\27\71\1\130\34\71\5\0\5\6"+
    "\1\131\7\6\6\0\13\6\26\0\7\6\1\132\5\6"+
    "\6\0\13\6\26\0\15\6\6\0\1\133\12\6\26\0"+
    "\12\6\1\134\2\6\6\0\13\6\26\0\15\6\6\0"+
    "\7\6\1\135\3\6\26\0\7\6\1\136\5\6\6\0"+
    "\13\6\26\0\12\6\1\137\2\6\6\0\13\6\26\0"+
    "\6\6\1\140\6\6\6\0\13\6\26\0\15\6\6\0"+
    "\1\141\12\6\26\0\15\6\6\0\2\6\1\142\10\6"+
    "\26\0\15\6\6\0\1\143\1\6\1\144\10\6\26\0"+
    "\15\6\6\0\10\6\1\145\2\6\26\0\7\6\1\146"+
    "\5\6\6\0\13\6\26\0\10\6\1\147\4\6\6\0"+
    "\13\6\26\0\12\6\1\150\2\6\6\0\13\6\26\0"+
    "\15\6\6\0\11\6\1\151\1\6\26\0\15\6\6\0"+
    "\1\152\12\6\21\0\26\71\1\4\1\130\34\71\5\0"+
    "\15\6\6\0\10\6\1\153\2\6\26\0\13\6\1\154"+
    "\1\6\6\0\13\6\26\0\14\6\1\155\6\0\13\6"+
    "\26\0\5\6\1\156\7\6\6\0\13\6\26\0\6\6"+
    "\1\157\6\6\6\0\13\6\26\0\5\6\1\160\7\6"+
    "\6\0\13\6\26\0\15\6\6\0\1\6\1\161\11\6"+
    "\26\0\13\6\1\162\1\6\6\0\13\6\26\0\15\6"+
    "\6\0\6\6\1\163\4\6\26\0\5\6\1\164\7\6"+
    "\6\0\13\6\26\0\13\6\1\165\1\6\6\0\13\6"+
    "\26\0\6\6\1\166\6\6\6\0\13\6\26\0\5\6"+
    "\1\167\7\6\6\0\13\6\26\0\15\6\6\0\7\6"+
    "\1\170\3\6\26\0\13\6\1\171\1\6\6\0\13\6"+
    "\26\0\10\6\1\172\4\6\6\0\13\6\26\0\14\6"+
    "\1\173\6\0\13\6\26\0\7\6\1\174\5\6\6\0"+
    "\13\6\26\0\12\6\1\175\2\6\6\0\13\6\26\0"+
    "\10\6\1\176\4\6\6\0\13\6\26\0\15\6\6\0"+
    "\1\177\12\6\26\0\15\6\6\0\7\6\1\200\3\6"+
    "\26\0\15\6\6\0\11\6\1\201\1\6\26\0\10\6"+
    "\1\202\4\6\6\0\13\6\26\0\12\6\1\203\2\6"+
    "\6\0\13\6\26\0\5\6\1\204\7\6\6\0\13\6"+
    "\26\0\15\6\6\0\5\6\1\205\5\6\26\0\15\6"+
    "\6\0\5\6\1\206\5\6\26\0\13\6\1\207\1\6"+
    "\6\0\13\6\26\0\10\6\1\210\4\6\6\0\13\6"+
    "\26\0\5\6\1\211\7\6\6\0\13\6\26\0\10\6"+
    "\1\212\4\6\6\0\13\6\26\0\15\6\6\0\1\6"+
    "\1\213\11\6\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4940];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\13\1\1\11\22\1\11\11"+
    "\1\1\1\0\6\1\6\0\1\11\15\1\7\11\7\1"+
    "\2\11\1\0\63\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
        public int getYyline() {
            return yyline;
        }

        public int getYychar() {
            return yychar;
        }

        public int getYycolumn() {
            return yycolumn;
        }
      public static int typeOperation;
      public static int typeIdentifier;
      public static int typeAccessModifier;
      public static int line;
      public static int dateType;
      public static int literalType;
      public static final int DATATYPE = 1;
      public static final int ID = 257;
      public static final int IF = 258;
      public static final int ELSE = 259;
      public static final int DO = 276;
      public static final int WHILE = 260;
      public static final int FOR = 261;
      public static final int CLASS = 277;
      public static final int PRIVATE = 278;
      public static final int PUBLIC = 279;
      public static final int PROTEC = 286;
      public static final int VOID = 280;
      public static final int RETURN = 281;
      public static final int ACCEMOD = 2;
      public static final int INT = 294;
      public static final int DOUBLE = 295;
      public static final int FLOAT = 296;
      public static final int BOOL = 297;
      public static final int LONG = 298;
      public static final int STRING = 299;
      public static final int CHAR = 300;
      public static final int VIRTUAL = 307;
      public static final int CIN = 309;
      public static final int COUT = 310;


      public static final int NUM = 262;
      public static final int REAL = 263;
      public static final int LITERAL =301;
      public static final int INTLITERAL =302;
      public static final int BOOLLITERAL =303;
      public static final int FLOATLITERAL =304;
      public static final int CHARLITERAL =305;
      public static final int STRINGLITERAL =306;

      public static final int ERROR = 0;

      public static final int OPERATION=3;
      public static final int ADD = 288;// +
      public static final int SUB = 289;//-
      public static final int MUL = 290;//*
      public static final int DIV = 291;// /
      public static final int MOD = 292;// %
      public static final int LT = 265;// <
      public static final int LE = 266;// <=
      public static final int EQ = 267;// ==
      public static final int NE = 268;// !=
      public static final int GT = 269;// >
      public static final int GE = 270;// >=
      public final static int AND = 282;// &&
      public final static int OR = 283;// ||
      public final static int ASSIGN = 293;// =
      public final static int FALSE = 284;// false
      public final static int TRUE = 285;// true
      public static final int NOT = 300;// !

      public static final int COMMA = 271;// ,
      public static final int COLON = 286;// :
      public static final int SEMICOLON = 287;// ;
      public static final int LPAREN = 272;// (
      public static final int RPAREN = 273;// )
      public static final int LBRACE = 274;//{
      public static final int RBRACE = 275;//}
      public static final int LBRACE1 = 307;//}
      public static final int RBRACE1 = 308;//}
      public static final int LSHIFT = 311;//<<
      public static final int RSHIFT = 312;//>>





  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return 0;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return ERROR;
            } 
            // fall through
          case 56: break;
          case 2: 
            { /* ignore */
            } 
            // fall through
          case 57: break;
          case 3: 
            { return ID;
            } 
            // fall through
          case 58: break;
          case 4: 
            { literalType = INTLITERAL; return LITERAL;
            } 
            // fall through
          case 59: break;
          case 5: 
            { return SEMICOLON;
            } 
            // fall through
          case 60: break;
          case 6: 
            { typeOperation =DIV; return OPERATION;
            } 
            // fall through
          case 61: break;
          case 7: 
            { typeOperation =MUL; return OPERATION;
            } 
            // fall through
          case 62: break;
          case 8: 
            { typeOperation =LT; return OPERATION;
            } 
            // fall through
          case 63: break;
          case 9: 
            { typeOperation =GT; return OPERATION;
            } 
            // fall through
          case 64: break;
          case 10: 
            { typeOperation = ADD; return OPERATION;
            } 
            // fall through
          case 65: break;
          case 11: 
            { typeOperation =ASSIGN; return OPERATION;
            } 
            // fall through
          case 66: break;
          case 12: 
            { typeOperation =SUB;return OPERATION;
            } 
            // fall through
          case 67: break;
          case 13: 
            { typeOperation =MOD; return OPERATION;
            } 
            // fall through
          case 68: break;
          case 14: 
            { typeOperation =NOT; return OPERATION;
            } 
            // fall through
          case 69: break;
          case 15: 
            { return COMMA;
            } 
            // fall through
          case 70: break;
          case 16: 
            { return COLON;
            } 
            // fall through
          case 71: break;
          case 17: 
            { return LPAREN;
            } 
            // fall through
          case 72: break;
          case 18: 
            { return RPAREN;
            } 
            // fall through
          case 73: break;
          case 19: 
            { return LBRACE;
            } 
            // fall through
          case 74: break;
          case 20: 
            { return RBRACE;
            } 
            // fall through
          case 75: break;
          case 21: 
            { return LBRACE1;
            } 
            // fall through
          case 76: break;
          case 22: 
            { return RBRACE1;
            } 
            // fall through
          case 77: break;
          case 23: 
            { typeOperation =AND; return OPERATION;
            } 
            // fall through
          case 78: break;
          case 24: 
            { literalType = FLOATLITERAL; return LITERAL;
            } 
            // fall through
          case 79: break;
          case 25: 
            { return OPERATION;
            } 
            // fall through
          case 80: break;
          case 26: 
            { return IF;
            } 
            // fall through
          case 81: break;
          case 27: 
            { return DO;
            } 
            // fall through
          case 82: break;
          case 28: 
            { return LSHIFT;
            } 
            // fall through
          case 83: break;
          case 29: 
            { typeOperation =LE; return OPERATION;
            } 
            // fall through
          case 84: break;
          case 30: 
            { return RSHIFT;
            } 
            // fall through
          case 85: break;
          case 31: 
            { typeOperation =GE; return OPERATION;
            } 
            // fall through
          case 86: break;
          case 32: 
            { typeOperation =EQ; return OPERATION;
            } 
            // fall through
          case 87: break;
          case 33: 
            { typeOperation =NE; return OPERATION;
            } 
            // fall through
          case 88: break;
          case 34: 
            { typeOperation =OR; return OPERATION;
            } 
            // fall through
          case 89: break;
          case 35: 
            { return FOR;
            } 
            // fall through
          case 90: break;
          case 36: 
            { literalType = CHARLITERAL; return LITERAL;
            } 
            // fall through
          case 91: break;
          case 37: 
            { literalType = STRINGLITERAL; return LITERAL;
            } 
            // fall through
          case 92: break;
          case 38: 
            { dateType = INT; return DATATYPE;
            } 
            // fall through
          case 93: break;
          case 39: 
            { return CIN;
            } 
            // fall through
          case 94: break;
          case 40: 
            { return ELSE;
            } 
            // fall through
          case 95: break;
          case 41: 
            { dateType = LONG; return DATATYPE;
            } 
            // fall through
          case 96: break;
          case 42: 
            { return COUT;
            } 
            // fall through
          case 97: break;
          case 43: 
            { dateType = CHAR; return DATATYPE;
            } 
            // fall through
          case 98: break;
          case 44: 
            { dateType = VOID; return DATATYPE;
            } 
            // fall through
          case 99: break;
          case 45: 
            { dateType = BOOL; return DATATYPE;
            } 
            // fall through
          case 100: break;
          case 46: 
            { dateType = FLOAT; return DATATYPE;
            } 
            // fall through
          case 101: break;
          case 47: 
            { return WHILE;
            } 
            // fall through
          case 102: break;
          case 48: 
            { return CLASS;
            } 
            // fall through
          case 103: break;
          case 49: 
            { return RETURN;
            } 
            // fall through
          case 104: break;
          case 50: 
            { dateType = STRING; return DATATYPE;
            } 
            // fall through
          case 105: break;
          case 51: 
            { dateType = DOUBLE; return DATATYPE;
            } 
            // fall through
          case 106: break;
          case 52: 
            { typeAccessModifier = PUBLIC;return ACCEMOD;
            } 
            // fall through
          case 107: break;
          case 53: 
            { return VIRTUAL;
            } 
            // fall through
          case 108: break;
          case 54: 
            { typeAccessModifier = PRIVATE;return ACCEMOD;
            } 
            // fall through
          case 109: break;
          case 55: 
            { typeAccessModifier = PROTEC;return ACCEMOD;
            } 
            // fall through
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
